const PROXY_TYPE_MAP = {
  HTTP: "PROXY",
  HTTPS: "HTTPS",
  SOCKS4: "SOCKS",
  SOCKS5: "SOCKS5"
};
const BUILT_IN_DIRECT_RULES = [
  "*.kis.v2.scr.kaspersky-labs.com",
  "trafficlight.bitdefender.com",
  "*.trafficlight.bitdefender.com",
  "safeweb.norton.com",
  "search.norton.com",
  "siteadvisor.com",
  "*.siteadvisor.com",
  "*.trustedsource.org"
];

export function normalizeHost(host) {
  const value = String(host || "")
    .trim()
    .toLowerCase()
    .replace(/\.$/, "");
  if (value.includes("/")) return value;
  const normalized = stripHostPort(value).replace(/^\[|\]$/g, "");
  return hostToAscii(normalized);
}

export function matchHostRule(host, rule) {
  const normalizedHost = normalizeHost(host);
  const pattern = normalizeRulePattern(rule);

  if (!normalizedHost || !pattern) return false;

  if (pattern.startsWith("*.")) {
    const suffix = pattern.slice(1);
    return normalizedHost.endsWith(suffix) && normalizedHost.length > suffix.length;
  }

  if (pattern.includes("*")) {
    const escaped = pattern
      .split("*")
      .map(escapeRegExp)
      .join(".*");
    return new RegExp(`^${escaped}$`, "i").test(normalizedHost);
  }

  return normalizedHost === pattern;
}

export function decideProxyRoute(config) {
  const enabled = Boolean(config?.enabled);
  const host = normalizeHost(config?.host);

  if (!enabled) return { action: "direct", reason: "disabled" };
  if (isPrivateHost(host)) return { action: "direct", reason: "private-ip" };
  const builtInDirectRule = findMatchingRule(host, normalizeRuleList(BUILT_IN_DIRECT_RULES));
  if (builtInDirectRule) {
    return {
      action: "direct",
      reason: "built-in-direct-rule",
      matchedRule: getRulePattern(builtInDirectRule)
    };
  }

  const rules = normalizeRules(config?.rules);
  const directRule = findMatchingRule(host, rules.direct);
  if (directRule) {
    return {
      action: "direct",
      reason: "direct-rule",
      matchedRule: getRulePattern(directRule)
    };
  }

  const proxyRule = findMatchingRule(host, rules.proxy);
  if (proxyRule) {
    const proxy = selectProxy(config?.proxies, proxyRule.proxyId || config?.activeProxyId);
    return {
      action: "proxy",
      reason: "proxy-rule",
      matchedRule: getRulePattern(proxyRule),
      proxy
    };
  }

  const geoip = config?.geoip || {};
  if (geoip.mode === "proxyNonLocal") {
    const hostCountry = normalizeCountry(geoip.hostCountry || geoip.hostCountries?.[host]);
    const localCountries = new Set((geoip.localCountries || []).map(normalizeCountry).filter(Boolean));

    if (hostCountry && localCountries.has(hostCountry)) {
      return { action: "direct", reason: "geoip-local", country: hostCountry };
    }

    if (hostCountry && !localCountries.has(hostCountry)) {
      return {
        action: "proxy",
        reason: "geoip-non-local",
        country: hostCountry,
        proxy: selectProxy(config?.proxies, config?.activeProxyId)
      };
    }
  }

  return { action: "direct", reason: "default-direct" };
}

export function formatProxyEndpoint(proxy) {
  if (!proxy) return "DIRECT";

  const type = PROXY_TYPE_MAP[String(proxy.type || "HTTP").toUpperCase()] || "PROXY";
  const host = String(proxy.host || "").trim();
  const port = Number(proxy.port);

  if (!host || !Number.isInteger(port) || port < 1 || port > 65535) {
    throw new Error(`Invalid proxy endpoint: ${JSON.stringify(proxy)}`);
  }

  return `${type} ${host}:${port}`;
}

export function buildPacScript(config) {
  const rules = normalizeRules(config?.rules);
  const proxies = Array.isArray(config?.proxies) ? config.proxies : [];
  const activeProxy = selectProxy(proxies, config?.activeProxyId);
  const proxyEndpoints = Object.fromEntries(proxies.map((proxy) => [proxy.id, formatProxyEndpoint(proxy)]));
  const defaultProxy = activeProxy ? formatProxyEndpoint(activeProxy) : "DIRECT";
  const hostCountries = config?.geoip?.hostCountries || {};
  const normalizedGeoIp = normalizeGeoIpRecords(hostCountries);
  const localCountries = (config?.geoip?.localCountries || []).map(normalizeCountry).filter(Boolean);

  return asciiSafeTemplate(`// Generated by Chrome AutoProxy. Do not edit manually.
const ENABLED = ${JSON.stringify(Boolean(config?.enabled))};
const BUILT_IN_DIRECT_RULES = ${JSON.stringify(BUILT_IN_DIRECT_RULES)};
const DIRECT_RULES = ${JSON.stringify(rules.direct.map(getRulePattern))};
const PROXY_RULES = ${JSON.stringify(rules.proxy.map((rule) => ({
    pattern: getRulePattern(rule),
    proxyId: rule.proxyId || null
  })))};
const PROXIES = ${JSON.stringify(proxyEndpoints)};
const DEFAULT_PROXY = ${JSON.stringify(defaultProxy)};
const HOST_COUNTRIES = ${JSON.stringify(normalizedGeoIp.hostCountries)};
const GEOIP_CIDRS = ${JSON.stringify(normalizedGeoIp.cidrs)};
const LOCAL_COUNTRIES = ${JSON.stringify(localCountries)};

function FindProxyForURL(url, host) {
  if (isLocalUrl(url)) return "DIRECT";
  host = normalizeHost(host);
  if (!ENABLED || isPrivateHost(host)) return "DIRECT";
  if (matchesAny(host, BUILT_IN_DIRECT_RULES)) return "DIRECT";
  if (matchesAny(host, DIRECT_RULES)) return "DIRECT";

  for (var i = 0; i < PROXY_RULES.length; i++) {
    if (matchHostRule(host, PROXY_RULES[i].pattern)) {
      return PROXIES[PROXY_RULES[i].proxyId] || ${JSON.stringify(defaultProxy)};
    }
  }

  var country = HOST_COUNTRIES[host] || findCidrCountry(host) || findResolvedCidrCountry(host);
  if (country) {
    if (LOCAL_COUNTRIES.indexOf(country) !== -1) return "DIRECT";
    return ${JSON.stringify(defaultProxy)};
  }

  return ${JSON.stringify(defaultProxy)};
}

function isLocalUrl(url) {
  url = String(url || "").toLowerCase();
  return /^https?:\\/\\/127(?:\\.\\d{1,3}){3}(?::\\d+)?(?:[\\/?#]|$)/.test(url) ||
    /^https?:\\/\\/localhost(?::\\d+)?(?:[\\/?#]|$)/.test(url) ||
    /^https?:\\/\\/\\[::1\\](?::\\d+)?(?:[\\/?#]|$)/.test(url);
}

function normalizeHost(host) {
  host = String(host || "").toLowerCase().replace(/\\.$/, "");
  if (host.indexOf("/") !== -1) return host;
  host = stripHostPort(host).replace(/^\\[|\\]$/g, "");
  return host;
}

function stripHostPort(host) {
  if (!host) return "";
  if (host.charAt(0) === "[") {
    var closeBracket = host.indexOf("]");
    return closeBracket === -1 ? host : host.slice(1, closeBracket);
  }
  if (host.indexOf(":") !== -1 && host.indexOf(":") === host.lastIndexOf(":")) {
    return host.split(":")[0];
  }
  return host;
}

function matchesAny(host, patterns) {
  for (var i = 0; i < patterns.length; i++) {
    if (matchHostRule(host, patterns[i])) return true;
  }
  return false;
}

function matchHostRule(host, pattern) {
  if (!host || !pattern) return false;
  if (pattern.indexOf("*.") === 0) {
    var suffix = pattern.slice(1);
    return host.slice(-suffix.length) === suffix && host.length > suffix.length;
  }
  if (pattern.indexOf("*") !== -1) {
    var escaped = pattern.replace(/[.+?^\${}()|[\\]\\\\]/g, "\\\\$&").replace(/\\*/g, ".*");
    return new RegExp("^" + escaped + "$", "i").test(host);
  }
  return host === pattern;
}

function isPrivateHost(host) {
  return host === "localhost" ||
    isReservedIpv4(host) ||
    /^10\\./.test(host) ||
    /^127\\./.test(host) ||
    /^192\\.168\\./.test(host) ||
    /^172\\.(1[6-9]|2[0-9]|3[0-1])\\./.test(host) ||
    /^169\\.254\\./.test(host) ||
    /^::1$/.test(host) ||
    /^fc00:/i.test(host) ||
    /^fd[0-9a-f]{2}:/i.test(host);
}

function isReservedIpv4(host) {
  if (!isIpv4(host)) return false;
  var value = ipv4ToInt(host);
  return value <= ipv4ToInt("0.255.255.255") ||
    value >= ipv4ToInt("10.0.0.0") && value <= ipv4ToInt("10.255.255.255") ||
    value >= ipv4ToInt("100.64.0.0") && value <= ipv4ToInt("100.127.255.255") ||
    value >= ipv4ToInt("127.0.0.0") && value <= ipv4ToInt("127.255.255.255") ||
    value >= ipv4ToInt("169.254.0.0") && value <= ipv4ToInt("169.254.255.255") ||
    value >= ipv4ToInt("172.16.0.0") && value <= ipv4ToInt("172.31.255.255") ||
    value >= ipv4ToInt("192.0.0.0") && value <= ipv4ToInt("192.0.0.255") ||
    value >= ipv4ToInt("192.0.2.0") && value <= ipv4ToInt("192.0.2.255") ||
    value >= ipv4ToInt("192.168.0.0") && value <= ipv4ToInt("192.168.255.255") ||
    value >= ipv4ToInt("198.18.0.0") && value <= ipv4ToInt("198.19.255.255") ||
    value >= ipv4ToInt("198.51.100.0") && value <= ipv4ToInt("198.51.100.255") ||
    value >= ipv4ToInt("203.0.113.0") && value <= ipv4ToInt("203.0.113.255") ||
    value >= ipv4ToInt("224.0.0.0") && value <= ipv4ToInt("255.255.255.255");
}

function findCidrCountry(host) {
  if (!isIpv4(host)) return "";
  for (var i = 0; i < GEOIP_CIDRS.length; i++) {
    if (isIpv4InCidr(host, GEOIP_CIDRS[i].cidr)) return GEOIP_CIDRS[i].country;
  }
  return "";
}

function findResolvedCidrCountry(host) {
  if (typeof dnsResolve !== "function") return "";
  var resolvedIp = dnsResolve(host);
  return resolvedIp ? findCidrCountry(resolvedIp) : "";
}

function isIpv4(value) {
  var parts = String(value).split(".");
  if (parts.length !== 4) return false;
  for (var i = 0; i < parts.length; i++) {
    var number = Number(parts[i]);
    if (!/^\\d+$/.test(parts[i]) || number < 0 || number > 255) return false;
  }
  return true;
}

function isIpv4InCidr(ip, cidr) {
  var pieces = cidr.split("/");
  var prefix = Number(pieces[1]);
  if (!isIpv4(pieces[0]) || !Number.isInteger(prefix) || prefix < 0 || prefix > 32) return false;
  var mask = prefix === 0 ? 0 : (0xffffffff << (32 - prefix)) >>> 0;
  return (ipv4ToInt(ip) & mask) === (ipv4ToInt(pieces[0]) & mask);
}

function ipv4ToInt(ip) {
  var parts = ip.split(".");
  var value = 0;
  for (var i = 0; i < parts.length; i++) {
    value = ((value << 8) + Number(parts[i])) >>> 0;
  }
  return value;
}
`);
}

export function isPrivateHost(host) {
  const normalizedHost = normalizeHost(host);
  return normalizedHost === "localhost" ||
    normalizedHost.endsWith(".local") ||
    isReservedIpv4(normalizedHost) ||
    /^10\./.test(normalizedHost) ||
    /^127\./.test(normalizedHost) ||
    /^192\.168\./.test(normalizedHost) ||
    /^172\.(1[6-9]|2[0-9]|3[0-1])\./.test(normalizedHost) ||
    /^169\.254\./.test(normalizedHost) ||
    /^::1$/.test(normalizedHost) ||
    /^fc00:/i.test(normalizedHost) ||
    /^fd[0-9a-f]{2}:/i.test(normalizedHost);
}

function isReservedIpv4(host) {
  if (!isIpv4(host)) return false;
  const value = ipv4ToInt(host);
  return isIpv4InRange(value, "0.0.0.0", "0.255.255.255") ||
    isIpv4InRange(value, "10.0.0.0", "10.255.255.255") ||
    isIpv4InRange(value, "100.64.0.0", "100.127.255.255") ||
    isIpv4InRange(value, "127.0.0.0", "127.255.255.255") ||
    isIpv4InRange(value, "169.254.0.0", "169.254.255.255") ||
    isIpv4InRange(value, "172.16.0.0", "172.31.255.255") ||
    isIpv4InRange(value, "192.0.0.0", "192.0.0.255") ||
    isIpv4InRange(value, "192.0.2.0", "192.0.2.255") ||
    isIpv4InRange(value, "192.168.0.0", "192.168.255.255") ||
    isIpv4InRange(value, "198.18.0.0", "198.19.255.255") ||
    isIpv4InRange(value, "198.51.100.0", "198.51.100.255") ||
    isIpv4InRange(value, "203.0.113.0", "203.0.113.255") ||
    isIpv4InRange(value, "224.0.0.0", "255.255.255.255");
}

function normalizeRules(rules = {}) {
  return {
    direct: normalizeRuleList(rules.direct),
    proxy: normalizeRuleList(rules.proxy)
  };
}

function normalizeRuleList(list = []) {
  return list
    .map((rule) => {
      if (typeof rule === "string") return { pattern: normalizeRulePattern(rule) };
      return { ...rule, pattern: normalizeRulePattern(rule?.pattern) };
    })
    .filter((rule) => rule.pattern);
}

function normalizeRulePattern(rule) {
  const pattern = String(rule || "").trim().toLowerCase().replace(/\.$/, "");
  if (pattern.startsWith("*.")) return `*.${hostToAscii(pattern.slice(2))}`;
  return hostToAscii(pattern);
}

function findMatchingRule(host, rules) {
  return rules.find((rule) => matchHostRule(host, rule.pattern));
}

function getRulePattern(rule) {
  return typeof rule === "string" ? normalizeRulePattern(rule) : normalizeRulePattern(rule?.pattern);
}

function selectProxy(proxies = [], proxyId) {
  if (!Array.isArray(proxies) || proxies.length === 0) return null;
  return proxies.find((proxy) => proxy.id === proxyId) || proxies[0];
}

function normalizeCountry(country) {
  const value = String(country || "").trim().toUpperCase();
  return /^[A-Z]{2}$/.test(value) ? value : "";
}

function hostToAscii(host) {
  if (!host || host.includes("*") || host.includes("/") || isIpv4(host)) return host;
  try {
    return new URL(`http://${host}`).hostname || host;
  } catch {
    return host;
  }
}

function stripHostPort(host) {
  if (!host) return "";
  try {
    return new URL(`http://${host}`).hostname;
  } catch {
    if (!host.startsWith("[") && host.includes(":") && host.indexOf(":") === host.lastIndexOf(":")) {
      return host.split(":")[0];
    }
    return host;
  }
}

function asciiSafeTemplate(value) {
  return value.replace(/[^\x00-\x7F]/g, (char) => {
    return `\\u${char.charCodeAt(0).toString(16).padStart(4, "0")}`;
  });
}

function isIpv4(value) {
  const parts = String(value).split(".");
  if (parts.length !== 4) return false;
  return parts.every((part) => {
    const number = Number(part);
    return /^\d+$/.test(part) && number >= 0 && number <= 255;
  });
}

function ipv4ToInt(ip) {
  return ip.split(".").reduce((value, part) => ((value << 8) + Number(part)) >>> 0, 0);
}

function isIpv4InRange(value, start, end) {
  return value >= ipv4ToInt(start) && value <= ipv4ToInt(end);
}

function normalizeCountryMap(hostCountries) {
  return Object.fromEntries(
    Object.entries(hostCountries)
      .map(([host, country]) => [normalizeHost(host), normalizeCountry(country)])
      .filter(([host, country]) => host && country)
  );
}

function normalizeGeoIpRecords(records) {
  const hostCountries = {};
  const cidrs = [];

  for (const [host, country] of Object.entries(records || {})) {
    const normalizedHost = normalizeHost(host);
    const normalizedCountry = normalizeCountry(country);
    if (!normalizedHost || !normalizedCountry) continue;

    if (normalizedHost.includes("/")) {
      cidrs.push({ cidr: normalizedHost, country: normalizedCountry });
    } else {
      hostCountries[normalizedHost] = normalizedCountry;
    }
  }

  return { hostCountries, cidrs };
}

function escapeRegExp(value) {
  return value.replace(/[.+?^${}()|[\]\\]/g, "\\$&");
}
